// Generated by ts-to-zod
import { z } from "zod";

const baseResponseSchema = z.any();

const searchResultSchema = z.any();

export const searchQueryResponseSchema = baseResponseSchema.extend({
  result: z.array(searchResultSchema),
});
