// Generated by ts-to-zod
import { z } from "zod";

const collectionTypeSchema = z.any();

const piiIdentifierOptionSchema = z.any();

const createCategoryPayloadSchema = z.any();

const baseResponseSchema = z.any();

export const createCollectionRequestSchema = z.object({
  organizationId: z.string(),
  name: z.string(),
  type: collectionTypeSchema,
  tags: z.array(z.string()).optional(),
  description: z.string().optional(),
  pii: z.boolean().optional(),
  piiControls: z.array(piiIdentifierOptionSchema).optional(),
  instructions: z.string().optional(),
  graphInstructions: z.string().optional(),
  promptInstructions: z.string().optional(),
  searchInstructions: z.string().optional(),
  categories: z.array(createCategoryPayloadSchema).optional(),
});

export const createCollectionResponseSchema = baseResponseSchema.extend({
  id: z.string(),
});
