// Generated by ts-to-zod
import { z } from "zod";

export const getCollectionRequestSchema = z.object({
  collectionId: z.string(),
});

const baseResponseSchema = z.any();

const collectionSchema = z.any();

const collectionStatsSchema = z.any();

export const getCollectionResponseSchema = baseResponseSchema.extend({
  result: collectionSchema.nullable(),
  stats: collectionStatsSchema.nullable(),
});
