// Generated by ts-to-zod
import { z } from "zod";

export const getCollectionsRequestSchema = z.object({
  search: z.string().optional(),
  take: z.number().optional(),
  skip: z.number().optional(),
  extended: z.boolean().optional(),
});

const baseResponseSchema = z.any();

const collectionSchema = z.any();

export const getCollectionsResponseSchema = baseResponseSchema.extend({
  result: z.array(collectionSchema),
});
