// Generated by ts-to-zod
import { z } from "zod";

const collectionTypeSchema = z.any();

const piiIdentifierOptionSchema = z.any();

const baseResponseSchema = z.any();

export const updateCollectionRequestSchema = z.object({
  collectionId: z.string(),
  organizationId: z.string().optional(),
  name: z.string().optional(),
  type: collectionTypeSchema.optional(),
  description: z.string().optional(),
  pii: z.boolean().optional(),
  piiControls: z.array(piiIdentifierOptionSchema).optional(),
  instructions: z.string().optional(),
  graphInstructions: z.string().optional(),
  promptInstructions: z.string().optional(),
  searchInstructions: z.string().optional(),
  tags: z.array(z.string()).optional(),
});

export const updateCollectionResponseSchema = baseResponseSchema;
