// Generated by ts-to-zod
import { z } from "zod";

export const featuresQueryRequestSchema = z.object({
  collectionId: z.string(),
  categoryId: z.string(),
  take: z.number().optional(),
  skip: z.number().optional(),
});

const baseResponseSchema = z.any();

const featureLayoutSchema = z.any();

export const featuresQueryResponseSchema = baseResponseSchema.extend({
  result: z.array(featureLayoutSchema),
});
