// Generated by ts-to-zod
import { z } from "zod";

export const exportTableRequestSchema = z.object({
  collectionId: z.string(),
  categoryId: z.string(),
  format: z.union([z.literal("json"), z.literal("csv")]).optional(),
  take: z.number().optional(),
  skip: z.number().optional(),
});

const baseResponseSchema = z.any();

export const exportTableResponseSchema = baseResponseSchema.extend({
  result: z.union([z.array(z.record(z.string())), z.string()]),
});
