// Generated by ts-to-zod
import { z } from "zod";

export const tablesQueryRequestSchema = z.object({
  collectionId: z.string(),
  categoryId: z.string(),
  skip: z.number().optional(),
  take: z.number().optional(),
  prompt: z.string().optional(),
});

const baseResponseSchema = z.any();

export const tablesQueryResponseSchema = baseResponseSchema.extend({
  result: z.array(z.record(z.string())),
});
