// Generated by ts-to-zod
import { z } from "zod";

export const createDocumentRequestSchema = z.object({
  collectionId: z.string(),
  name: z.string(),
  path: z.string(),
  type: z.string(),
  instructions: z.string().optional(),
  job: z.boolean().optional(),
  tables: z.boolean().optional(),
});

const baseResponseSchema = z.any();

export const createDocumentResponseSchema = baseResponseSchema.extend({
  id: z.string(),
});
