// Generated by ts-to-zod
import { z } from "zod";

export const deleteDocumentRequestSchema = z.object({
  collectionId: z.string(),
  documentId: z.string(),
});

const baseResponseSchema = z.any();

export const deleteDocumentResponseSchema = baseResponseSchema;
