// Generated by ts-to-zod
import { z } from "zod";

export const exportDocumentRequestSchema = z.object({
  collectionId: z.string(),
  documentId: z.string(),
  type: z.union([z.literal("json"), z.literal("text")]).optional(),
});

const documentLayoutSchema = z.any();

const audioLayoutSchema = z.any();

const photoLayoutSchema = z.any();

const videoLayoutSchema = z.any();

export const exportDocumentResponseSchema = z.union([
  z.array(documentLayoutSchema),
  z.array(audioLayoutSchema),
  z.array(photoLayoutSchema),
  z.array(videoLayoutSchema),
  z.string(),
]);
