// Generated by ts-to-zod
import { z } from "zod";

export const getDocumentRequestSchema = z.object({
  collectionId: z.string(),
  documentId: z.string(),
});

const baseResponseSchema = z.any();

const documentSchema = z.any();

export const getDocumentResponseSchema = baseResponseSchema.extend({
  result: documentSchema.nullable(),
});
