// Generated by ts-to-zod
import { z } from "zod";

const jobStatusSchema = z.any();

const baseResponseSchema = z.any();

const documentSchema = z.any();

export const getDocumentsRequestSchema = z.object({
  collectionId: z.string(),
  search: z.string().optional(),
  take: z.number().optional(),
  skip: z.number().optional(),
  extended: z.boolean().optional(),
  status: jobStatusSchema.optional(),
  nodes: jobStatusSchema.optional(),
  edges: jobStatusSchema.optional(),
  vectors: jobStatusSchema.optional(),
  category: jobStatusSchema.optional(),
});

export const getDocumentsResponseSchema = baseResponseSchema.extend({
  result: z.array(documentSchema),
});
