// Generated by ts-to-zod
import { z } from "zod";

const jobTypeSchema = z.any();

const baseResponseSchema = z.any();

export const reprocessDocumentsRequestSchema = z.object({
  collectionId: z.string(),
  ids: z.array(z.string()),
  type: jobTypeSchema,
});

export const reprocessDocumentsResponseSchema = baseResponseSchema;
