// Generated by ts-to-zod
import { z } from "zod";

export const updateDocumentRequestSchema = z.object({
  collectionId: z.string(),
  documentId: z.string(),
  name: z.string().optional(),
  instructions: z.string().optional(),
  tables: z.boolean().optional(),
  job: z.boolean().optional(),
});

const baseResponseSchema = z.any();

export const updateDocumentResponseSchema = baseResponseSchema;
