// Generated by ts-to-zod
import { z } from "zod";

export const statusTypeSchema = z.union([z.literal("OK"), z.literal("ERROR")]);

export const baseRequestSchema = z.object({
  apiKey: z.string(),
  apiUrl: z.string(),
  debug: z.boolean(),
});

export const baseResponseSchema = z.object({
  status: statusTypeSchema,
  message: z.string().optional(),
});
