// Generated by ts-to-zod
import { z } from "zod";

const layoutTypeSchema = z.any();

const jobSchema = z.any();

const documentLayoutSchema = z.any();

const photoLayoutSchema = z.any();

const videoLayoutSchema = z.any();

const audioLayoutSchema = z.any();

export const documentSchema = z.object({
  id: z.string(),
  collectionId: z.string(),
  name: z.string(),
  type: z.string(),
  layoutType: layoutTypeSchema,
  layoutNodes: z.number(),
  tables: z.boolean(),
  instructions: z.string(),
  job: jobSchema.optional(),
  layout: z
    .union([
      z.array(documentLayoutSchema),
      z.array(photoLayoutSchema),
      z.array(videoLayoutSchema),
      z.array(audioLayoutSchema),
    ])
    .optional(),
  metadata: z
    .object({
      size: z.number(),
      pages: z.number(),
      length: z.number(),
    })
    .optional(),
  dateCreated: z.date(),
  dateUpdated: z.date(),
});
