// Generated by ts-to-zod
import { z } from "zod";

export const jobTypeSchema = z.union([
  z.literal("status"),
  z.literal("nodes"),
  z.literal("vectors"),
  z.literal("edges"),
  z.literal("category"),
]);

export const jobStatusSchema = z.union([
  z.literal("processing"),
  z.literal("error"),
  z.literal("ready"),
  z.literal("cancelled"),
  z.literal("unprocessed"),
  z.literal("partial"),
  z.literal("all"),
]);

const layoutTypeSchema = z.any();

export const jobSchema = z.object({
  id: z.string(),
  collectionId: z.string(),
  documentId: z.string(),
  status: jobStatusSchema,
  nodes: jobStatusSchema,
  edges: jobStatusSchema,
  vectors: jobStatusSchema,
  category: jobStatusSchema,
  message: z.string(),
  document: z
    .object({
      id: z.string(),
      collectionId: z.string(),
      dateCreated: z.date(),
      dateUpdated: z.date(),
      name: z.string(),
      type: z.string(),
      layoutType: layoutTypeSchema,
      layoutNodes: z.number(),
      instructions: z.string(),
    })
    .optional(),
  dateCreated: z.date(),
  dateUpdated: z.date(),
});
