// Generated by ts-to-zod
import { z } from "zod";

export const layoutTypeSchema = z.union([
  z.literal("document"),
  z.literal("photo"),
  z.literal("audio"),
  z.literal("video"),
]);

export const layoutPositionSchema = z.tuple([
  z.number(),
  z.number(),
  z.number(),
  z.number(),
]);

export const documentLayoutOutputSchema = z.object({
  position: layoutPositionSchema,
  type: z.union([
    z.literal("title"),
    z.literal("subtitle"),
    z.literal("list"),
    z.literal("text"),
    z.literal("table"),
    z.literal("image"),
    z.literal("csv"),
    z.string(),
  ]),
  content: z.string(),
});

export const documentLayoutSchema = documentLayoutOutputSchema.extend({
  index: z.number(),
  page: z.number(),
});

export const audioLayoutSchema = z.object({
  index: z.number(),
  start: z.string(),
  end: z.string(),
  narrator: z.string(),
  description: z.string(),
  content: z.string(),
});

export const photoLayoutSchema = z.object({
  position: layoutPositionSchema,
  description: z.string(),
  type: z.string(),
});

export const videoLayoutSchema = z.object({
  index: z.number(),
  start: z.string(),
  end: z.string(),
  audio: z.string(),
  narration: z.string(),
  narrator: z.string(),
  objects: z.array(photoLayoutSchema),
});

export const featureLayoutSchema = z.object({
  position: z.array(z.number()),
  label: z.string(),
  description: z.string(),
});
