// Generated by ts-to-zod
import { z } from "zod";

export const organizationPlanSchema = z.union([
  z.literal("preview"),
  z.literal("developer"),
  z.literal("starter"),
  z.literal("scale"),
  z.literal("enterprise"),
]);

export const membershipRoleSchema = z.union([
  z.literal("member"),
  z.literal("admin"),
]);

export const organizationListResultSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  plan: organizationPlanSchema,
  status: z.string(),
  dateCreated: z.date(),
  dateUpdated: z.date(),
  members: z
    .array(
      z.object({
        id: z.string(),
        accountId: z.string(),
        role: membershipRoleSchema,
        organization: z.object({
          id: z.string(),
          name: z.string(),
          description: z.string(),
          plan: organizationPlanSchema,
        }),
        account: z.object({
          id: z.string(),
          email: z.string(),
          verified: z.boolean(),
          dateCreated: z.date(),
          dateUpdated: z.date(),
        }),
        dateCreated: z.date(),
        dateUpdated: z.date(),
      }),
    )
    .optional(),
});

export const organizationResultSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  plan: organizationPlanSchema,
  status: z.string(),
  dateCreated: z.date(),
  dateUpdated: z.date(),
  members: z.array(
    z.object({
      organization: z.object({
        id: z.string(),
        name: z.string(),
        description: z.string(),
        plan: organizationPlanSchema,
      }),
      id: z.string(),
      dateCreated: z.date(),
      dateUpdated: z.date(),
      accountId: z.string(),
      role: membershipRoleSchema,
      account: z.object({
        id: z.string(),
        name: z.string(),
        email: z.string(),
      }),
    }),
  ),
  collections: z.array(
    z.object({
      id: z.string(),
      name: z.string(),
      dateCreated: z.date(),
      dateUpdated: z.date(),
    }),
  ),
});

export const organizationMemberRequestSchema = z.object({
  id: z.string(),
  role: membershipRoleSchema,
});
